In [86]:
# Library
# 这个是用来判断点在不在多边形里面的库，同时绘制点和多边形
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon
# 这里是用这个来读取shapefile文件
import shapefile
import pandas as pd
import numpy as np

In [16]:
# Load the shapefile information
sf = shapefile.Reader("./2019ParcelPointsNoDups/2019ParcelPointsNoDups.shp") # note, no suffix, all 3 files are used
recs = sf.records()
shapes = sf.shapes()

In [17]:
recs

[Record #0: ['0100001000', '', '0100001000', 'PASCUCCI CARLO', '104 A 104', 'PUTNAM', 'ST', '', '02128', 'R3', '105', 1150, '195 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'Y', 3353, 2202, 541200.0, 129900, 411300, 5704.25, 3.0, '0100001000', '104 A 104 PUTNAM ST, 02128', 'EAST BOSTON', 210.2109375, 65.8426763, 210.2109375, 65.8426762964, 1, -71.032587507, 42.3793853109],
 Record #1: ['0100002000', '', '0100002000', 'ATANASOV DANIEL', '197', 'LEXINGTON', 'ST', '', '02128', 'R3', '105', 1150, '197 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'N', 3299, 2307, 596100.0, 121000, 475100, 6282.89, 3.0, '0100002000', '197   LEXINGTON ST, 02128', 'EAST BOSTON', 197.875, 64.69736635, 197.875, 64.6973663526, 2, -71.0325209187, 42.3794119758],
 Record #2: ['0100003000', '', '0100003000', 'CHEVARRIA ANA S', '199', 'LEXINGTON', 'ST', '', '02128', 'R3', '105', 1150, '199 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'N', 3392, 2268, 542500.0, 121400, 421100, 5717.95, 3.0, '0100003000', '199   LEXINGTON ST, 

In [22]:
df = pd.DataFrame(recs) 

In [23]:
df.head()

0  1           2                      3          4          5   6   \
0  0100001000     0100001000         PASCUCCI CARLO  104 A 104     PUTNAM  ST   
1  0100002000     0100002000        ATANASOV DANIEL        197  LEXINGTON  ST   
2  0100003000     0100003000        CHEVARRIA ANA S        199  LEXINGTON  ST   
3  0100004000     0100004000  MADDALENI JAMES E, TS        201  LEXINGTON  ST   
4  0100005000     0100005000      DIGIROLAMO JOHN A        203  LEXINGTON  ST   

  7      8   9   ...          23                          24           25  \
0     02128  R3  ...  0100001000  104 A 104 PUTNAM ST, 02128  EAST BOSTON   
1     02128  R3  ...  0100002000   197   LEXINGTON ST, 02128  EAST BOSTON   
2     02128  R3  ...  0100003000   199   LEXINGTON ST, 02128  EAST BOSTON   
3     02128  R3  ...  0100004000   201   LEXINGTON ST, 02128  EAST BOSTON   
4     02128  R2  ...  0100005000   203   LEXINGTON ST, 02128  EAST BOSTON   

           26          27          28          29  30         31         32  
0  210.210938   65.842676  210.210938   65.842676   1 -71.032588  42.379385  
1  197.875000   64.697366  197.875000   64.697366   2 -71.032521  42.379412  
2  195.144531   64.345174  195.144531   64.345174   3 -71.032455  42.379436  
3  203.187500   64.898348  203.187500   64.898348   4 -71.032390  42.379463  
4  367.007812  102.429328  367.007812  102.429328   5 -71.032282  42.379430  

[5 rows x 33 columns]

In [90]:
test = df[df[10].isin([986])]
pd.set_option('display.max_columns', None)
test.head(20)

0 1           2                             3          4  \
387   0100364000    0100364000       MASSACHUSETTS PORT AUTH        411   
388   0100365010    0100365010          MASS BAY TRANSP AUTH              
424   0100410000    0100410000  MASSACHUSETTS PORT AUTHORITY        423   
434   0100428010    0100428010          MASS BAY TRANSP AUTH              
435   0100429000    0100429000  MASSACHUSETTS PORT AUTHORITY        418   
437   0100431000    0100431000       MASSACHUSETTS PORT AUTH        406   
441   0100433000    0100433000          CITY OF BOSTON (FCL)              
447   0100436001    0100436001   MASS DEPT OF TRANSPORTATION              
450   0100437100    0100437100             MASSACHUSETTS BAY              
451   0100438000    0100438000          COMMONWEALTH OF MASS              
455   0100439030    0100439030      MASSACHUSETTS DEPARTMENT        611   
458   0100441060    0100441060  MASSACHUSETTS PORT AUTHORITY              
501   0100485010    0100485010            MASSPORT AUTHORITY              
1441  0101358000    0101358000  METROPOLITAN DIST COMMISSION              
1480  0101391000    0101391000    DEPARTMENT OF PUBLIC WORKS  1026 1034   
1482  0101392001    0101392001    DEPARTMENT OF PUBLIC WORKS              
1485  0101393001    0101393001         CITY OF BOSTON BY FCL        150   
4307  0103918000    0103918000  E BOSTON NEIGHBORHOOD HEALTH              
4309  0103918055    0103918055      CITY OF BOSTON PARKS AND              
4310  0103919001    0103919001      EAST BOSTON NEIGHBORHOOD      135 B   

                        5   6 7      8  9   10      11  \
387             FRANKFORT  ST    02128  E  986    2217   
388             FRANKFORT  ST    02128  E  986    4240   
424            BENNINGTON  ST    02128  E  986    3159   
434             FRANKFORT  ST    02128  E  986    3274   
435             FRANKFORT  ST    02128  E  986    4727   
437             FRANKFORT  ST    02128  E  986    3500   
441         CHELSEA CREEK        02128  E  986   36932   
447   BOSTON AND MAINE RR        02128  E  986   22000   
450        WM F MCCLELLAN  HW    02128  E  986   47267   
451        WM F MCCLELLAN  HW    02128  E  986   95164   
455               CHELSEA  ST    02128  E  986   20530   
458               CHELSEA  ST    02128  E  986    7665   
501        WM F MCCLELLAN  HW    02128  E  986  195447   
1441             SARATOGA  ST    02128  E  986  492800   
1480             SARATOGA  ST    02128  E  986    4583   
1482           BENNINGTON  ST    02128  E  986    3960   
1485               BARNES  AV    02128  E  986  109175   
4307               BREMEN  ST    02128  E  986   28720   
4309             MAVERICK  ST    02128  E  986   26997   
4310               BREMEN  ST    02128  E  986   63996   

                                12              13     14 15    16    17  \
387          1 HARBORSIDE DR #200S  EAST BOSTON MA  02128  N     0     0   
388                   FRANKFORT ST  EAST BOSTON MA  02128  N     0     0   
424          1 HARBORSIDE DR #200S  EAST BOSTON MA  02128  N     0     0   
434                    FRANFORT ST  EAST BOSTON MA  02128  N     0     0   
435          1 HARBORSIDE DR #200S  EAST BOSTON MA  02128  N     0     0   
437   ONE HARBORSIDE DRIVE SUITE 2  EAST BOSTON MA  02128  N     0     0   
441            N TERM BLD L AIRPRT  EAST BOSTON MA  02128  N     0     0   
447                  10 PARK PLAZA       BOSTON MA  02116  N     0     0   
450               WM F MCLELLAN HW  EAST BOSTON MA  02128  N     0     0   
451                 20 SOMERSET ST       BOSTON MA  02108  N     0     0   
455                 611 CHELSEA ST  EAST BOSTON MA  02128  N     0     0   
458                     CHELSEA ST  EAST BOSTON MA  02128  N     0     0   
501              WM F MCCLEELAN HW  EAST BOSTON MA  02128  N     0     0   
1441                      SARATOGA  EAST BOSTON MA  02128  N     0     0   
1480              1026 SARATOGA ST  EAST BOSTON MA  02128  N     0     0   
1482

In [58]:
df_ptype = df[[10, 32,31]]
df[10] = df[10].astype(np.int32)
df[32] = df[32].astype(np.float64)
df[31] = df[31].astype(np.float64)
# df_ptype = pd.to_numeric(df_ptype)
# df_ptype = pd.DataFrame(df_ptype)
df_ptype

10         32         31
0       105  42.379387 -71.032585
1       105  42.379414 -71.032524
2       105  42.379436 -71.032455
3       105  42.379463 -71.032387
4       104  42.379429 -71.032280
...     ...        ...        ...
171917  902  42.340874 -71.166618
171918  132  42.340519 -71.166664
171919  105  42.340527 -71.166389
171920  319  42.340279 -71.166451
171921  985  42.340759 -71.166969

[171922 rows x 3 columns]

In [72]:
df_data_1 = df_ptype[df_ptype[10].isin([986])]
df_data_1 = df_data_1.values.astype(np.float64)
for l in df_data_1:
    print(l)

[986.          42.37970352 -71.02339172]
[986.          42.37978363 -71.02326965]
[986.          42.38031769 -71.0238266 ]
[986.          42.37996292 -71.02336884]
[986.          42.38005066 -71.02365875]
[986.          42.37989807 -71.02380371]
[986.          42.3961525  -71.01386261]
[986.          42.38483047 -71.02109528]
[986.          42.38491821 -71.02061462]
[986.          42.3866539  -71.02001953]
[986.          42.38560486 -71.02175903]
[986.          42.38323212 -71.0227356 ]
[986.          42.38150406 -71.02394867]
[986.          42.38376236 -70.99664307]
[986.          42.38635254 -71.00551605]
[986.          42.38664246 -71.00606537]
[986.          42.38454437 -70.99505615]
[986.          42.370327   -71.03697968]
[986.          42.37032318 -71.03675842]
[986.          42.37139893 -71.03553772]
[986.          42.37135315 -71.03508759]
[986.          42.37309265 -71.03343964]
[986.          42.37469101 -71.03153229]
[986.          42.37665558 -71.02928925]
[986.          4

In [78]:
df_data_1 = df_ptype[df_ptype[10].isin([986])]
vacant1 = df_data_1[[32, 31]].values.astype(np.float64)
count = 1
for l in vacant1:
    print(str(count) + " " + str(l[0])+","+str(l[1]))
    count += 1

1 42.379703521728516,-71.02339172363281
2 42.379783630371094,-71.02326965332031
3 42.38031768798828,-71.0238265991211
4 42.37996292114258,-71.02336883544922
5 42.38005065917969,-71.0236587524414
6 42.37989807128906,-71.0238037109375
7 42.39615249633789,-71.01386260986328
8 42.384830474853516,-71.0210952758789
9 42.384918212890625,-71.02061462402344
10 42.386653900146484,-71.02001953125
11 42.38560485839844,-71.02175903320312
12 42.38323211669922,-71.02273559570312
13 42.38150405883789,-71.0239486694336
14 42.38376235961914,-70.99664306640625
15 42.3863525390625,-71.0055160522461
16 42.38664245605469,-71.00606536865234
17 42.384544372558594,-70.99505615234375
18 42.37032699584961,-71.03697967529297
19 42.370323181152344,-71.03675842285156
20 42.37139892578125,-71.03553771972656
21 42.37135314941406,-71.03508758544922
22 42.37309265136719,-71.03343963623047
23 42.374691009521484,-71.03153228759766
24 42.37665557861328,-71.02928924560547
25 42.37754440307617,-71.02825164794922
26 42.37466

In [93]:
df_data_1 = df_ptype[df_ptype[10].isin([962])]
vacant1 = df_data_1[[32, 31]].values.astype(np.float64)
count = 1
for l in vacant1:
    print(str(count) + " " + str(l[0])+","+str(l[1]))
    count += 1

1 42.34966278076172,-71.0606918334961
2 42.343162536621094,-71.0537109375
3 42.342952728271484,-71.05387115478516
4 42.33478927612305,-71.04396057128906
5 42.347354888916016,-71.03535461425781
6 42.346946716308594,-71.03643035888672
7 42.34359359741211,-71.03621673583984
8 42.34364700317383,-71.03462982177734
9 42.32857894897461,-71.0669174194336
10 42.33482360839844,-71.07000732421875
11 42.33359146118164,-71.07166290283203
12 42.330406188964844,-71.0850601196289
13 42.3203010559082,-71.04613494873047
14 42.311580657958984,-71.0633773803711
15 42.364688873291016,-71.12208557128906
16 42.357994079589844,-71.1473617553711


In [89]:
# Build a list to hold the ploygon represent the subsurb
sub_plon = []
for item in shapes:
    # Using the points information to draw the ploygon
    polygon = Polygon(item.points)
    sub_plon.append(polygon)
# Drow one of the subsurb
sub_plon[0]

ValueError: A LinearRing must have at least 3 coordinate tuples